package com.example.demo1;

/*
  JavaFX Application Skeleton (Generated by IntelliJ IDEA IDE)
  This file is for creating the window for our application
  It's the entry point to run our application since it has the main method
  So you can just click the "run" green arrow button
 */

// Importing all the needed JavaFX libraries:
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
/*
HelloApplication class is our main class that extends the "Application" abstract class:
so all JavaFX application must extend the "Application" class
*/
public class HelloApplication extends Application {

    /*
    * Our main class "HelloApplication":
    * > overrides "start()" method start() method
    * is the entry point for the JavaFX Applications
    *
    * > declares the primary/main stage called "stage" of type "Stage"
    * every JavaFx App has a primary stage
    *
    * stage has a scene that contains the JavaFX nodes (components in Swing)
    *
    * No GUI buttons/components and no controls for events in this file:
    * - the GUI nodes will be defined in the .fxml file
    * - the events will be defined in the .java controller file
    */
    @Override
    public void start(Stage stage) throws IOException {
        /*
        * FXMLLoader => loading the object graph hierarchy from our .fxml file "hello-view.fxml"
        */
        FXMLLoader fxmlLoader = new FXMLLoader(HelloApplication.class.getResource("hello-view.fxml"));

        /*
        Starting and setting a new Scene instance "scene" for our application window:
        setting the width and height in pixels
        */
        Scene scene = new Scene(fxmlLoader.load(), 320, 240);

        /*
        Setting the primary stage window
        */
        // Give the stage a title (a title for the application window)
        stage.setTitle("Hello to JavaFX!");

        // Set the scene on the stage:
        stage.setScene(scene);

        // Show the stage and its scene:
        stage.show();
    }

    public static void main(String[] args) {
        // Start the JavaFX application by calling launch() to launch our application :-)
        launch();
    }
}